### ISSUE TITLE
Create interactive CLI

### ISSUE THREAD

**Issue by ikke09** [ikke09/codewars-cli#1]
# TODO
- [x] Install dependencies
  - [x] [https://www.npmjs.com/package/inquirer](https://www.npmjs.com/package/inquirer)
- [ ] Implement flow
  - [x] Ask for Access Token
  - [ ] Ask for programming language
  - [ ] Ask for url / id / slug of the kata
  - [ ] Create directory with kata name
  - [ ] Create Readme.md with informations about the kata
  - [ ] Create testfile and solution file based on language

## Bonus
- [ ] Check codewars-api if we can retrieve given test cases and implementation and write them into the starter files
