### ISSUE TITLE
Create Pipeline with Github-Actions

### ISSUE THREAD

**Issue by ikke09** [ikke09/codewars-cli#2]
# TODO
- [ ] Setup build pipeline for pr verification
  - [ ] Run tests
  - [ ] Build npm package
- [ ] Setup release pipeline
  - [ ] Publish package to NPM
